---
jenkins_port: 8080
minio_port: 9000
s3www_port: 80
testapi_port: 8000
registry_port: 5000
jenkins_user: admin
jenkins_password: admin
project: xtesting
slave:
block_level_key: block-level
sudo1:
use_testapi: true
use_jenkins: true
jenkins_workspace: /data/jenkins/workspace
publish:
  db: true
  cmd: mc cp -r
  repo: minio/{{ project }}
  www: http://127.0.0.1
docker_tags:
docker_args:
  env: {}
  volumes: []
triggers:
  - timed: '@daily'
suites:
  - repo: opnfv
    container: xtesting
    tests:
      - first
      - second
      - third
      - fourth
      - fifth
